/**
 * The Worker — Hono API.
 *
 * The middleware order below is the security design, and it is order-sensitive.
 * Read it top to bottom before changing it.
 */

import { Hono } from 'hono';
import { api } from './routes';
import { reporting } from './routes-reporting';
import { csrfGuard, privateAuth, publicAuth, requireSession, securityHeaders } from './auth';

/**
 * Bindings. `DB` and `ASSETS` come from worker-configuration.d.ts, generated by
 * `wrangler types` from wrangler.jsonc, so they cannot drift from what is
 * actually deployed. Rerun `wrangler types` after changing bindings.
 *
 * AUTH_SECRET is a secret, not a binding, so it is declared here. Unset ⇒ the
 * auth gate is DISABLED — local development only (§16.1).
 *
 * APP_ENV is a plain var, declared in wrangler.jsonc and therefore already on
 * the generated type — 'production' only under `env.production`. It is what
 * lets the Worker tell "the gate is off because this is a laptop" from "the
 * gate is off because a secret went missing in production".
 */
export interface Env extends Cloudflare.Env {
  AUTH_SECRET?: string;
}

const app = new Hono<{ Bindings: Env }>();

// 1. §16.2 — the six security headers on EVERY response, including static
//    assets and errors. First in, so nothing can return ahead of it.
app.use('*', securityHeaders);

/**
 * 2. §16.1 — "the build must refuse to start in production mode without it".
 *
 * A missing `AUTH_SECRET` silently disables the gate, which would leave the
 * entire financial history readable by anyone with the URL. That is the worst
 * failure this application has, so production refuses to serve anything at all
 * rather than serving it unprotected. Fail closed, loudly, on the first request.
 */
app.use('*', async (c, next) => {
  if (c.env.APP_ENV === 'production' && !c.env.AUTH_SECRET) {
    return c.text(
      'Refusing to serve: AUTH_SECRET is not set in production. ' +
        'Run `wrangler secret put AUTH_SECRET --env production` and redeploy.',
      503,
      { 'cache-control': 'no-store' },
    );
  }
  return next();
});

// 3. §16.3 — CSRF. Ahead of the gate, so a cross-site request is refused before
//    its cookie is even looked at.
app.use('/api/*', csrfGuard);

// 4. The three PUBLIC auth routes (§14): login, me, logout. Mounted before the
//    gate rather than excepted from inside it — an exception list is the kind
//    of thing a later route quietly falls off.
app.route('/api', publicAuth);

// 5. §16.3 — the gate. Everything below this line is 401 without a session, so
//    there is no unauthenticated read of financial data and no unauthenticated
//    write path. Adding a route below it is secure by default; that is the
//    point of putting it here rather than per-route.
app.use('/api/*', requireSession);

app.route('/api', privateAuth);
app.route('/api', api);
app.route('/api', reporting);

app.get('/api/health', (c) =>
  c.json({
    ok: true,
    phase: 3,
    // Never echo money or dealer details into a response body that could be
    // logged (§16.3). A health check carries neither.
    authGate: c.env.AUTH_SECRET ? 'enabled' : 'DISABLED — local development only',
  }),
);

// An unknown /api path is a JSON 404 — never the SPA shell, which would hand a
// fetch() an HTML body and produce a confusing parse error instead of a clear
// one. Error responses carry a stable `code` (§14).
app.all('/api/*', (c) => c.json({ error: { code: 'NOT_FOUND', message: 'No such route.' } }, 404));

/**
 * Everything else is the SPA shell.
 *
 * The shell is served unauthenticated, deliberately: it is an empty document
 * plus a script bundle and contains no dealer, no amount, and no balance. It
 * has to be reachable for the login form to be drawn at all. Every byte of
 * actual data arrives over `/api`, which is behind the gate above — so §16.1's
 * "gates the entire application" is satisfied where it matters, at the data.
 */
app.all('*', (c) => c.env.ASSETS.fetch(c.req.raw));

/**
 * Uncaught errors — §14 and §16.3.
 *
 * Hono's default handler answers `text/plain` "Internal Server Error" and logs
 * the whole stack. Two things are wrong with that here:
 *
 *   - §14: every error response carries a stable machine-readable `code`. A
 *     plain-text body makes the client's `res.json()` fall through to its
 *     generic "something went wrong", so a real server fault is indistinguishable
 *     from a dropped connection — and on a ledger, knowing which one happened
 *     decides whether the owner re-enters the amount or not.
 *   - §16.3: no money or dealer PII in logs. `observability` is on, so whatever
 *     is logged leaves the Worker. The request body — where every amount and
 *     dealer name lives — is never touched here, and the thrown text is never
 *     returned to the client.
 *
 * The security headers are already on this response: `securityHeaders` is the
 * outermost middleware and Hono applies the error handler beneath it.
 */
app.onError((err, c) => {
  const { pathname } = new URL(c.req.url);
  console.error(`${c.req.method} ${pathname} failed: ${err.name}: ${err.message}`);

  if (pathname.startsWith('/api/')) {
    return c.json(
      {
        error: {
          code: 'INTERNAL',
          // Deliberately fixed text. The thrown message may name a table, a
          // column or a constraint, and none of that belongs in a response.
          //
          // It does NOT claim nothing was written. A throw can land after a
          // batch has committed — the follow-up read in createTransaction is
          // exactly such a place — and telling the owner "nothing was changed"
          // would invite a duplicate entry. Sending them to look is the only
          // honest answer.
          message:
            'Something went wrong on the server. Check whether the entry was saved before trying again.',
        },
      },
      500,
    );
  }
  return c.text('Something went wrong.', 500);
});

export default app;
