/**
 * The Worker — Hono API.
 *
 * PHASE 1: dealer, transaction and payment routes over the posting layer.
 *
 * ⚠ Still to come in Phase 3: the auth gate (§16.1) in front of everything, and
 * the six security headers (§16.2) on every response. SRS §16.3 requires every
 * ledger-mutating endpoint to sit behind the session check, with no
 * unauthenticated write path — and this Worker now HAS write paths. The gate
 * must be in place before any real data is entered.
 */

import { Hono } from 'hono';
import { api } from './routes';

/**
 * Bindings. `DB` and `ASSETS` come from worker-configuration.d.ts, generated by
 * `wrangler types` from wrangler.jsonc, so they cannot drift from what is
 * actually deployed. Rerun `wrangler types` after changing bindings.
 *
 * AUTH_SECRET is a secret, not a binding, so it is declared here. Unset ⇒ the
 * auth gate is DISABLED — local development only (§16.1).
 */
export interface Env extends Cloudflare.Env {
  AUTH_SECRET?: string;
}

const app = new Hono<{ Bindings: Env }>();

app.route('/api', api);

app.get('/api/health', (c) =>
  c.json({
    ok: true,
    phase: 1,
    // Never echo money or dealer details into a response body that could be
    // logged (§16.3). A health check carries neither.
    authGate: c.env.AUTH_SECRET ? 'enabled' : 'DISABLED — local development only',
  }),
);

// An unknown /api path is a JSON 404 — never the SPA shell, which would hand a
// fetch() an HTML body and produce a confusing parse error instead of a clear
// one. Error responses carry a stable `code` (§14).
app.all('/api/*', (c) => c.json({ error: { code: 'NOT_FOUND', message: 'No such route.' } }, 404));

// Everything else is the SPA. `not_found_handling: single-page-application`
// means the assets binding returns index.html for any path that is not a built
// file, so client-side routes like /dealers/1 resolve (§10.2).
app.all('*', (c) => c.env.ASSETS.fetch(c.req.raw));

export default app;
