/**
 * The Worker — Hono API.
 *
 * The middleware order below is the security design, and it is order-sensitive.
 * Read it top to bottom before changing it.
 */

import { Hono } from 'hono';
import { bodyLimit } from 'hono/body-limit';
import { MoneyRangeError } from '../money';
import { WriteConflict } from '../posting/write';
import { api } from './routes';
import { reporting } from './routes-reporting';
import { csrfGuard, privateAuth, publicAuth, requireSession, securityHeaders } from './auth';

/**
 * Bindings. `DB` and `ASSETS` come from worker-configuration.d.ts, generated by
 * `wrangler types` from wrangler.jsonc, so they cannot drift from what is
 * actually deployed. Rerun `wrangler types` after changing bindings.
 *
 * AUTH_SECRET is a secret, not a binding, so it is declared here. Unset ⇒ the
 * auth gate is DISABLED — local development only (§16.1).
 *
 * APP_ENV is a plain var, declared in wrangler.jsonc and therefore already on
 * the generated type — 'production' only under `env.production`. It is what
 * lets the Worker tell "the gate is off because this is a laptop" from "the
 * gate is off because a secret went missing in production".
 */
export interface Env extends Cloudflare.Env {
  AUTH_SECRET?: string;
}

const app = new Hono<{ Bindings: Env }>();

// 1. §16.2 — the six security headers on EVERY response, including static
//    assets and errors. First in, so nothing can return ahead of it.
app.use('*', securityHeaders);

// Private JSON and auth responses must not be retained by HTTP caches,
// including callers other than our no-store fetch helper.
app.use('/api/*', async (c, next) => {
  await next();
  c.header('Cache-Control', 'no-store');
});

/**
 * 1b. HTTPS only, in production.
 *
 * HSTS protects a browser that has already visited over https. It does nothing
 * for the first request typed as plain http, and on that request the sign-in
 * form would post the password unencrypted. Local development is http and is
 * left alone.
 */
app.use('*', async (c, next) => {
  const url = new URL(c.req.url);
  if (c.env.APP_ENV === 'production' && url.protocol === 'http:') {
    url.protocol = 'https:';
    return c.redirect(url.toString(), 301);
  }
  return next();
});

/**
 * 2. §16.1 — "the build must refuse to start in production mode without it".
 *
 * A missing `AUTH_SECRET` silently disables the gate, which would leave the
 * entire financial history readable by anyone with the URL. That is the worst
 * failure this application has, so production refuses to serve anything at all
 * rather than serving it unprotected. Fail closed, loudly, on the first request.
 */
app.use('*', async (c, next) => {
  if (c.env.APP_ENV === 'production' && !c.env.AUTH_SECRET) {
    return c.text(
      'Refusing to serve: AUTH_SECRET is not set in production. ' +
        'Run `wrangler secret put AUTH_SECRET --env production` and redeploy.',
      503,
      { 'cache-control': 'no-store' },
    );
  }
  return next();
});

// 3. §16.3 — CSRF. Ahead of the gate, so a cross-site request is refused before
//    its cookie is even looked at.
app.use('/api/*', csrfGuard);
app.use(
  '/api/*',
  bodyLimit({
    maxSize: 256 * 1024,
    onError: (c) =>
      c.json(
        {
          error: {
            code: 'BODY_TOO_LARGE',
            message: 'This entry is too large. Shorten the notes or use fewer lines.',
          },
        },
        413,
      ),
  }),
);
app.use('/api/*', async (c, next) => {
  const key = c.req.header('Idempotency-Key');
  if (key !== undefined && !/^[A-Za-z0-9_-]{16,128}$/.test(key)) {
    return c.json({ error: { code: 'VALIDATION_FAILED', message: 'Invalid save key.' } }, 400);
  }
  return next();
});

// 4. The three PUBLIC auth routes (§14): login, me, logout. Mounted before the
//    gate rather than excepted from inside it — an exception list is the kind
//    of thing a later route quietly falls off.
app.route('/api', publicAuth);

// 5. §16.3 — the gate. Everything below this line is 401 without a session, so
//    there is no unauthenticated read of financial data and no unauthenticated
//    write path. Adding a route below it is secure by default; that is the
//    point of putting it here rather than per-route.
app.use('/api/*', requireSession);

app.route('/api', privateAuth);
app.route('/api', api);
app.route('/api', reporting);

app.get('/api/health', (c) =>
  c.json({
    ok: true,
    phase: 3,
    // Never echo money or dealer details into a response body that could be
    // logged (§16.3). A health check carries neither.
    authGate: c.env.AUTH_SECRET ? 'enabled' : 'DISABLED — local development only',
  }),
);

// An unknown /api path is a JSON 404 — never the SPA shell, which would hand a
// fetch() an HTML body and produce a confusing parse error instead of a clear
// one. Error responses carry a stable `code` (§14).
app.all('/api/*', (c) => c.json({ error: { code: 'NOT_FOUND', message: 'No such route.' } }, 404));

/**
 * RFC 9116 — where to report a security problem.
 *
 * Served by the Worker rather than from public/.well-known, because a
 * dot-directory is exactly what the asset upload and the file-like 404 rule
 * below both treat as suspect.
 *
 * `Expires` is required and must be under a year out. It is computed — one year
 * from the first of the current month — rather than hard-coded, so it never
 * silently lapses. The contact is maintained here in code, which is what keeps
 * a rolling date honest: if this address changes, this line changes with it.
 */
const SECURITY_CONTACT = 'mailto:suhaib.muhammed2002@gmail.com';

app.get('/.well-known/security.txt', (c) => {
  const now = new Date();
  const expires = new Date(Date.UTC(now.getUTCFullYear() + 1, now.getUTCMonth(), 1));
  const { origin } = new URL(c.req.url);
  return c.text(
    [
      `Contact: ${SECURITY_CONTACT}`,
      `Expires: ${expires.toISOString()}`,
      'Preferred-Languages: en',
      `Canonical: ${origin}/.well-known/security.txt`,
      '',
    ].join('\n'),
    200,
    { 'cache-control': 'public, max-age=86400' },
  );
});

/**
 * A missing build asset is a real 404 — never the SPA shell. The same reasoning
 * as /api above, and it has already broken the live site once.
 *
 * Bundles are content-hashed, so every deploy renames them. Any page still
 * holding the previous HTML — an open tab, or a service-worker cache — asks for
 * `/assets/index-<old hash>.js`, which no longer exists. `single-page-application`
 * not-found handling answered that with index.html and a 200. The browser then
 * refused to execute HTML as a module script and the owner got a blank white
 * page, with the real cause ("Expected a JavaScript module script but the server
 * responded with a MIME type of text/html") only visible in DevTools.
 *
 * Worse, a 200 is cacheable: the service worker stored that HTML under the .js
 * URL. A 404 is not, so the mistake cannot persist.
 *
 * Nothing under /assets/ is ever legitimately HTML, which is what makes the
 * content-type a safe signal that the fallback fired.
 */
app.get('/assets/*', async (c) => {
  const res = await c.env.ASSETS.fetch(c.req.raw);
  if (res.headers.get('content-type')?.startsWith('text/html')) {
    return c.text('Not found', 404);
  }
  if (!res.ok) return res;

  // Content-hashed, so a given URL can never change: cache it for a year. The
  // HTML that names these files stays max-age=0, which is what makes a deploy
  // take effect.
  const cached = new Response(res.body, res);
  cached.headers.set('cache-control', 'public, max-age=31536000, immutable');
  return cached;
});

/**
 * Everything else is the SPA shell.
 *
 * The shell is served unauthenticated, deliberately: it is an empty document
 * plus a script bundle and contains no dealer, no amount, and no balance. It
 * has to be reachable for the login form to be drawn at all. Every byte of
 * actual data arrives over `/api`, which is behind the gate above — so §16.1's
 * "gates the entire application" is satisfied where it matters, at the data.
 */
app.all('*', async (c) => {
  const res = await c.env.ASSETS.fetch(c.req.raw);

  /*
   * A request for a FILE that does not exist is a real 404, not the app shell.
   * `/.env`, `/.git/HEAD`, `/backup.zip`: none of these exist, but the SPA
   * fallback answered each with index.html and a 200, which every security
   * scanner reports as an exposed secret. App routes never contain a dot or a
   * dot-segment, so this cannot catch one.
   */
  const { pathname } = new URL(c.req.url);
  const segments = pathname.split('/').filter(Boolean);
  const fileLike =
    segments.some((s) => s.startsWith('.')) || (segments.at(-1)?.includes('.') ?? false);
  if (fileLike && res.headers.get('content-type')?.startsWith('text/html')) {
    return c.text('Not found', 404);
  }
  return res;
});

/**
 * Uncaught errors — §14 and §16.3.
 *
 * Hono's default handler answers `text/plain` "Internal Server Error" and logs
 * the whole stack. Two things are wrong with that here:
 *
 *   - §14: every error response carries a stable machine-readable `code`. A
 *     plain-text body makes the client's `res.json()` fall through to its
 *     generic "something went wrong", so a real server fault is indistinguishable
 *     from a dropped connection — and on a ledger, knowing which one happened
 *     decides whether the owner re-enters the amount or not.
 *   - §16.3: no money or dealer PII in logs. `observability` is on, so whatever
 *     is logged leaves the Worker. The request body — where every amount and
 *     dealer name lives — is never touched here, and the thrown text is never
 *     returned to the client.
 *
 * The security headers are already on this response: `securityHeaders` is the
 * outermost middleware and Hono applies the error handler beneath it.
 */
app.onError((err, c) => {
  if (err instanceof WriteConflict || err instanceof MoneyRangeError) {
    return c.json(
      {
        error: {
          code: err instanceof MoneyRangeError ? 'AMOUNT_OUT_OF_RANGE' : 'WRITE_CONFLICT',
          message: err.message,
        },
      },
      err instanceof MoneyRangeError ? 400 : 409,
    );
  }
  const { pathname } = new URL(c.req.url);
  // ORM exception messages can contain SQL parameters, including private data.
  console.error(`${c.req.method} request failed: ${err.name}`);

  if (pathname.startsWith('/api/')) {
    return c.json(
      {
        error: {
          code: 'INTERNAL',
          // Deliberately fixed text. The thrown message may name a table, a
          // column or a constraint, and none of that belongs in a response.
          //
          // It does NOT claim nothing was written. A throw can land after a
          // batch has committed — the follow-up read in createTransaction is
          // exactly such a place — and telling the owner "nothing was changed"
          // would invite a duplicate entry. Sending them to look is the only
          // honest answer.
          message:
            'Something went wrong on the server. Check whether the entry was saved before trying again.',
        },
      },
      500,
    );
  }
  return c.text('Something went wrong.', 500);
});

export default app;
