// `TEST_MIGRATIONS` is supplied by vitest.config.ts and exists only under test.
// The real bindings come from worker-configuration.d.ts, generated by
// `wrangler types` from wrangler.jsonc — so they can never drift from the
// bindings the Worker is actually deployed with.
declare namespace Cloudflare {
  interface Env {
    TEST_MIGRATIONS: import('@cloudflare/vitest-pool-workers').D1Migration[];
  }
}
